name: location_checker
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^9.0.0  # Get user location
  latlong2: ^0.8.1    # Calculate distance
  intl: ^0.20.2
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  http: ^1.3.0
  path: ^1.8.3
  connectivity_plus: ^6.1.3
  table_calendar: ^3.0.5
  flutter_dotenv: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background.png
    - assets/images/logo.jpeg
    - assets/data/credentials.json
    - assets/images/punchin.png
    - assets/images/punchout.png
    - assets/images/totalhours.png